@MininalsApi_HostAddress = http://localhost:5152

### Post
POST {{MininalsApi_HostAddress}}/administradores
Accept: application/json
Content-Type: application/json

{
"email" : "admin@email.com",
"password": "123456",
"perfil": "Admin"
}

### Login
POST {{MininalsApi_HostAddress}}/administradores/login
Accept: application/json
Content-Type: application/json

{
"email" : "admin@email.com",
"password": "123456"
}

### GetAll
GET {{MininalsApi_HostAddress}}/administradores
Accept: application/json
